#if !canImport(ObjectiveC)
import XCTest

extension ModelGeneratorTest {
    // DO NOT MODIFY: This is autogenerated, use:
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__ModelGeneratorTest = [
        ("testArrayObjectWithArrayFieldOfIntsStringsAndDoubles", testArrayObjectWithArrayFieldOfIntsStringsAndDoubles),
        ("testArrayObjectWithArrayFieldOfUnknownTypeAndStrings", testArrayObjectWithArrayFieldOfUnknownTypeAndStrings),
        ("testArrayObjectWithMixedFieldOfMixedArraysAndInt", testArrayObjectWithMixedFieldOfMixedArraysAndInt),
        ("testArrayOfEmptyObject", testArrayOfEmptyObject),
        ("testArrayOfEmptyOptionalObject", testArrayOfEmptyOptionalObject),
        ("testArrayOfMixedBoolAndDouble", testArrayOfMixedBoolAndDouble),
        ("testArrayOfMixedBoolIntAndDouble", testArrayOfMixedBoolIntAndDouble),
        ("testArrayOfMixedIntAndFloat", testArrayOfMixedIntAndFloat),
        ("testArrayOfMixedIntFloatAndDouble", testArrayOfMixedIntFloatAndDouble),
        ("testArrayOfObjectsWithMissingField", testArrayOfObjectsWithMissingField),
        ("testArrayOfObjectsWithMixedTypesAndOptional", testArrayOfObjectsWithMixedTypesAndOptional),
        ("testBool", testBool),
        ("testDouble", testDouble),
        ("testEmptyArray", testEmptyArray),
        ("testEmptyObject", testEmptyObject),
        ("testEqualNumberTypes", testEqualNumberTypes),
        ("testEqualTypeEnum", testEqualTypeEnum),
        ("testEqualTypeList", testEqualTypeList),
        ("testEqualTypeNumber", testEqualTypeNumber),
        ("testEqualTypeObject", testEqualTypeObject),
        ("testEqualTypeOptional", testEqualTypeOptional),
        ("testEqualTypeText", testEqualTypeText),
        ("testEqualTypeUnknown", testEqualTypeUnknown),
        ("testFloat", testFloat),
        ("testInt", testInt),
        ("testIntArray", testIntArray),
        ("testNullArray", testNullArray),
        ("testOptionalStringArray", testOptionalStringArray),
        ("testSingleFieldObject", testSingleFieldObject),
        ("testString", testString),
        ("testStringArray", testStringArray),
        ("testThreeFieldsObject", testThreeFieldsObject),
        ("testTransformAllFieldsToOptional", testTransformAllFieldsToOptional),
        ("testTransformAllFieldsToOptionalWithToplevelEnum", testTransformAllFieldsToOptionalWithToplevelEnum),
        ("testTransformAllFieldsToOptionalWithToplevelList", testTransformAllFieldsToOptionalWithToplevelList),
        ("testUInt", testUInt),
    ]
}

public func __allTests() -> [XCTestCaseEntry] {
    return [
        testCase(ModelGeneratorTest.__allTests__ModelGeneratorTest),
    ]
}
#endif
