#if !canImport(ObjectiveC)
import XCTest

extension ModelGeneratorCommandLineTest {
    // DO NOT MODIFY: This is autogenerated, use:
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__ModelGeneratorCommandLineTest = [
        ("testAllFieldsOptionalFlag", testAllFieldsOptionalFlag),
    ]
}

extension ObjcModelCreatorCommandLineTest {
    // DO NOT MODIFY: This is autogenerated, use:
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__ObjcModelCreatorCommandLineTest = [
        ("testAtomicFieldsFlag", testAtomicFieldsFlag),
        ("testMutableFieldsFlag", testMutableFieldsFlag),
        ("testPrefixOption", testPrefixOption),
        ("testReverseMappingFlag", testReverseMappingFlag),
    ]
}

extension ReverseJsonTest {
    // DO NOT MODIFY: This is autogenerated, use:
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__ReverseJsonTest = [
        ("testConsoleOutput", testConsoleOutput),
        ("testExistingOutputButNotADir", testExistingOutputButNotADir),
        ("testFileOutput", testFileOutput),
        ("testHasUsage", testHasUsage),
        ("testInvalidJson", testInvalidJson),
        ("testModelName", testModelName),
        ("testNoArguments", testNoArguments),
        ("testNonExistingFile", testNonExistingFile),
        ("testNonExistingOutputDir", testNonExistingOutputDir),
        ("testObjc", testObjc),
        ("testOutDir", testOutDir),
        ("testParsedJson", testParsedJson),
        ("testPassArgumentsToModelGenerator", testPassArgumentsToModelGenerator),
        ("testPassArgumentsToTranslator", testPassArgumentsToTranslator),
        ("testSwift", testSwift),
        ("testUnknownLanguage", testUnknownLanguage),
        ("testVerbose", testVerbose),
        ("testWrongArgumentCount", testWrongArgumentCount),
    ]
}

extension SwiftTranslatorCommandLineTest {
    // DO NOT MODIFY: This is autogenerated, use:
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__SwiftTranslatorCommandLineTest = [
        ("testClassFlag", testClassFlag),
        ("testContiguousArrayFlag", testContiguousArrayFlag),
        ("testMutableFieldsFlag", testMutableFieldsFlag),
        ("testPublicFieldsFlag", testPublicFieldsFlag),
        ("testPublicTypeFlagWithObject", testPublicTypeFlagWithObject),
    ]
}

public func __allTests() -> [XCTestCaseEntry] {
    return [
        testCase(ModelGeneratorCommandLineTest.__allTests__ModelGeneratorCommandLineTest),
        testCase(ObjcModelCreatorCommandLineTest.__allTests__ObjcModelCreatorCommandLineTest),
        testCase(ReverseJsonTest.__allTests__ReverseJsonTest),
        testCase(SwiftTranslatorCommandLineTest.__allTests__SwiftTranslatorCommandLineTest),
    ]
}
#endif
