#if !canImport(ObjectiveC)
import XCTest

extension SwiftTranslatorTest {
    // DO NOT MODIFY: This is autogenerated, use:
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__SwiftTranslatorTest = [
        ("testBoolDouble", testBoolDouble),
        ("testClassFlag", testClassFlag),
        ("testContiguousArrayFlag", testContiguousArrayFlag),
        ("testEmptyEnum", testEmptyEnum),
        ("testEmptyObject", testEmptyObject),
        ("testEnumWithOneCase", testEnumWithOneCase),
        ("testEnumWithOneSubDeclarationCase", testEnumWithOneSubDeclarationCase),
        ("testEnumWithTwoCases", testEnumWithTwoCases),
        ("testListOfEmptyObject", testListOfEmptyObject),
        ("testListOfTextList", testListOfTextList),
        ("testListOfUnknown", testListOfUnknown),
        ("testMutableFieldsFlag", testMutableFieldsFlag),
        ("testObjectWithFieldContainingListOfText", testObjectWithFieldContainingListOfText),
        ("testObjectWithOneFieldWithSubDeclaration", testObjectWithOneFieldWithSubDeclaration),
        ("testObjectWithSingleTextField", testObjectWithSingleTextField),
        ("testObjectWithTwoSimpleFields", testObjectWithTwoSimpleFields),
        ("testOptionalText", testOptionalText),
        ("testOptionalUnknown", testOptionalUnknown),
        ("testPublicFieldsFlag", testPublicFieldsFlag),
        ("testPublicTypeFlagWithEnum", testPublicTypeFlagWithEnum),
        ("testPublicTypeFlagWithObject", testPublicTypeFlagWithObject),
        ("testPublicTypeFlagWithTypealias", testPublicTypeFlagWithTypealias),
        ("testSimpleDouble", testSimpleDouble),
        ("testSimpleFloat", testSimpleFloat),
        ("testSimpleInt", testSimpleInt),
        ("testSimpleString", testSimpleString),
        ("testTextList", testTextList),
        ("testTranslatorCombination", testTranslatorCombination),
        ("testUnknownType", testUnknownType),
    ]
}

public func __allTests() -> [XCTestCaseEntry] {
    return [
        testCase(SwiftTranslatorTest.__allTests__SwiftTranslatorTest),
    ]
}
#endif
