#if !canImport(ObjectiveC)
import XCTest

extension ObjcModelTranslatorTest {
    // DO NOT MODIFY: This is autogenerated, use:
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__ObjcModelTranslatorTest = [
        ("testAtomicFieldsFlag", testAtomicFieldsFlag),
        ("testBoolDouble", testBoolDouble),
        ("testEmptyEnum", testEmptyEnum),
        ("testEmptyObject", testEmptyObject),
        ("testEnumWithOneCase", testEnumWithOneCase),
        ("testEnumWithOneCaseAndReverseMapping", testEnumWithOneCaseAndReverseMapping),
        ("testEnumWithTwoCases", testEnumWithTwoCases),
        ("testEnumWithTwoCasesAndReverseMapping", testEnumWithTwoCasesAndReverseMapping),
        ("testListOfEmptyObject", testListOfEmptyObject),
        ("testMutableFieldsFlag", testMutableFieldsFlag),
        ("testNamedEmptyEnum", testNamedEmptyEnum),
        ("testNamedEmptyObject", testNamedEmptyObject),
        ("testNamedEnumWithTwoCasesAndReverseMapping", testNamedEnumWithTwoCasesAndReverseMapping),
        ("testObjectWithDifferentFields", testObjectWithDifferentFields),
        ("testObjectWithFieldContainingListOfText", testObjectWithFieldContainingListOfText),
        ("testObjectWithFieldContainingListOfTextWithReverseMapper", testObjectWithFieldContainingListOfTextWithReverseMapper),
        ("testObjectWithFieldContainingOptionalListOfText", testObjectWithFieldContainingOptionalListOfText),
        ("testObjectWithOneFieldWithSubDeclaration", testObjectWithOneFieldWithSubDeclaration),
        ("testObjectWithSingleReservedTextField", testObjectWithSingleReservedTextField),
        ("testObjectWithSingleTextField", testObjectWithSingleTextField),
        ("testObjectWithSingleTextFieldAndReverseMapper", testObjectWithSingleTextFieldAndReverseMapper),
        ("testPrefixOption", testPrefixOption),
        ("testSimpleDouble", testSimpleDouble),
        ("testSimpleFloat", testSimpleFloat),
        ("testSimpleInt", testSimpleInt),
        ("testSimpleString", testSimpleString),
        ("testTextList", testTextList),
        ("testUnknownType", testUnknownType),
    ]
}

public func __allTests() -> [XCTestCaseEntry] {
    return [
        testCase(ObjcModelTranslatorTest.__allTests__ObjcModelTranslatorTest),
    ]
}
#endif
